HCMS/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import handler404, handler500
from HCMS_System_Admin.system_admin.views import search_result
from activity_log.views import sysparam_load 
  
urlpatterns = [      
    url(r'^admin/', admin.site.urls),     
    url(r'',include('activity_log.urls', namespace="login")), 
    url(r'hcms/', include('hcms_dashboard.urls', namespace="dashboard")),
    url(r'search_result/$', search_result, name='search_result'),
    url(r'sysparam_load/$', sysparam_load, name='sysparam_load'), 
    url(r'', include('HCMS_System_Admin.help_topics.urls', namespace="help_content")),
    url(r'', include('HCMS_System_Admin.system_admin.urls', namespace="hcms_sysadmin")),
    url(r'', include('HCMS_System_Admin.appserver.urls', namespace="hcms_appserver")),
    url(r'', include('HCMS_System_Admin.correspondence_mgt.urls', namespace="hcms_correspondence")), # 26-Mar-2018 || SMI || Added Correspondence Management Main URL
    url(r'', include('Talent_Inventory.talent_inventory.urls', namespace="talent_inventory")), # 08-Feb-2018 || SMI || Added Talent Inventory Main URL
    url(r'', include('Talent_Assessment.assessment_template_form.urls', namespace="ta_assessment_template_form")), #Added- ESK -07Feb2018
    url(r'', include('Talent_Assessment.cascading_objectives.urls', namespace="ta_cascading")), #Added- Bav -07Feb2018
    url(r'', include('Talent_Assessment.balanced_scorecard.urls', namespace="ta_balanced_scorecard")), #Added- Bav -23Feb2018
    url(r'', include('Talent_Assessment.assessment_custom_rating.urls', namespace="ta_customrating")), #Added- SAR -07Feb2018
    url(r'', include('Talent_Assessment.assessment_schedule.urls', namespace="ta_schedule_group")), #Added- SAR -07Feb2018
    url(r'', include('Talent_Assessment.talent_assessment.urls', namespace="ta_performance_assessment")), #Added- ESK -07Feb2018
    url(r'', include('HRMS_Foundation.attendance_management.urls', namespace="hrms_attendance")),
    url(r'', include('HRMS_Foundation.employee_management.urls', namespace="hrms_employee")),
    url(r'', include('Talent_Assessment.ta_reports.urls', namespace="ta_reports")), #Added- SND -13Feb2018
    url(r'', include('Talent_Assessment.ta_dashboard.urls', namespace="ta_dashboard")), #Added- SAR -27Feb2018
    url(r'', include('Comprehensive_Management.comprehensive_management.urls', namespace="base_employee")), #Added- BAV -27Feb2018
    url(r'', include('Workforce_Administration.workforce_administration.urls', namespace="workforce_administration")), #Added- SYA -03Apr2018
    url(r'', include('HRMS_Foundation.payroll_management.urls', namespace="payroll_management")), #Added- ESK -04-04-2018
    url(r'', include('Incident_Management.incident_management.urls', namespace="incident_details_recording")), #Added- ESK -04-04-2018
    url(r'', include('Exit_Management.exit_management.urls', namespace="exit_management")), # 18-May-2018 || SMI || Added Exit Management Main URL
    url(r'', include('Asset_Management.asset_management.urls', namespace="asset_management")), #Added- MST -16-05-2018     
    url(r'', include('Workforce_Administration.shift_management.urls', namespace="shift_management")), #Added- JAN -18-05-2018        
    url(r'', include('Workforce_Administration.time_attendance_management.urls', namespace="attendance_management")),
    url(r'', include('Talent_Acquisition.talent_acquisition.urls', namespace="talent_acquisition")),
    url(r'', include('Workforce_Planning.workforce_planning.urls', namespace="workforce_planning")), # 04-July-2018 || SMI || Added Workforce Planning Main URL
    url(r'', include('NTree.urls', namespace="ntree")),
    url(r'', include('Performance_Management.objective_setting.urls', namespace="objective_setting")),
    url(r'', include('Performance_Management.performance_assessment.urls', namespace="performance_assessment")),
    url(r'', include('Succession_Planning.succession_planning.urls', namespace="succession_planning")),
    url(r'', include('Talent_Management.talent_management.urls', namespace="talent_management")),
    url(r'', include('Learning_Management.learning_management.urls', namespace="learning_management")),
    url(r'performance/', include('Performance_Assessment.PerformanceAssessment.urls', namespace="performance_assessment_monthly")),
    url(r'cs/', include('Correspondance_Management_Static.CorrespondanceManagementStatic.urls', namespace="correspondance_management_static")),
    url(r'', include('MyNext_Dashboard.communication_empowerment.urls', namespace="communication_empowerment")),
    url(r'', include('MyNext_Dashboard.communication_empowerment.api_urls', namespace="communication_empowerment_api")),
    url(r'', include('CommonLib.urls', namespace="CommonLib_api")),
    url(r'', include('payment.urls', namespace="payment")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'hcms_dashboard.views.error_404'

HCMS_System_Admin/help_topics/urls.py
from django.conf.urls import url, include
from .views import HelpContentDetailsView, HelpContentAppDetailsView, HelpContentAppSysAdminDetailsView, sub_module_data

urlpatterns = [
    url(r'^help_content/$', HelpContentDetailsView.as_view(), name='help_content_page'),
    url(r'^help_content_app/$', HelpContentAppDetailsView.as_view(), name='help_content_page1'),
    url(r'^help_content_details/(?P<module_name>\w{0,50})/$', HelpContentAppSysAdminDetailsView.as_view(), name='help_content_details'),
    url(r'^help_content_details/(?P<module_name>\w{0,50})/(?P<sub_module_name>\w{0,50})/$', sub_module_data, name='help_content_sub_module'),
]

HCMS_System_Admin/help_topics/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

HCMS_System_Admin/help_topics/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import json
import os
from django.views.generic.base import TemplateView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.http.response import HttpResponse
import HCMS.settings as status_keys
from django.template import loader
import logging
import logging.handlers
logger_obj = logging.getLogger('logit')

# from UAM.uam_session_sync import uam_sessions_sync
# from UAM.uam_func_data_sync import uam_func_sync
# from tracking.models import Visitor

class HelpContentDetailsView(TemplateView):
    ''' 
        15-Feb-2018 || ANT || To HCMS system admin help content details module loaded
        @param request: Request Object
        @type request : Object
        @return:   HttpResponse or Redirect the another URL
    '''
    
    template_name = "help_topics/help_content_info.html"
    
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(HelpContentDetailsView, self).dispatch(request, *args, **kwargs)
    
    def get(self, request, *args, **kwargs):
        context = super(HelpContentDetailsView, self).get_context_data(**kwargs)
        return self.render_to_response(context)
    
class HelpContentAppDetailsView(TemplateView):
    ''' 
        15-Feb-2018 || ANT || To HCMS system admin help content app details module loaded
        @param request: Request Object
        @type request : Object
        @return:   HttpResponse or Redirect the another URL
    '''
    
    template_name = "help_topics/help_content_app_info.html"
    
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(HelpContentAppDetailsView, self).dispatch(request, *args, **kwargs)
    
    def get(self, request, *args, **kwargs):
        context = super(HelpContentAppDetailsView, self).get_context_data(**kwargs)
        return self.render_to_response(context)
    
class HelpContentAppSysAdminDetailsView(TemplateView):
    ''' 
        15-Feb-2018 || ANT || To HCMS system admin help content app full details module loaded
        @param request: Request Object
        @type request : Object
        @return:   HttpResponse or Redirect the another URL
    '''
    def get_template_names(self):
        module_name = self.kwargs['module_name']
        if module_name == "SysAdmin":
            template_name = "help_topics/SysAdmin/sysadmin_content_info.html"
        elif module_name == "HRMS":
            template_name = "help_topics/HRMS/hrms_content_info.html"
        elif module_name == "TalentDefinition":
			template_name = "help_topics/TalentDefinition/td_content_info.html"
        elif module_name == "TalentAssessment":
			template_name = "help_topics/TalentAssessment/ta_content_info.html"
        elif module_name == "WorkforcePlanning":
			template_name = "help_topics/WorkforcePlanning/wp_content_info.html"
        return [template_name]

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(HelpContentAppSysAdminDetailsView, self).dispatch(request, *args, **kwargs)
    
    def get(self, request, *args, **kwargs):
        context = super(HelpContentAppSysAdminDetailsView, self).get_context_data(**kwargs)
        return self.render_to_response(context)

def sub_module_data(request, **kwargs):
    ''' 
        02-Mar-2018 || ANT || To HCMS system admin help content sub module data fetch
        @param request: Request Object
        @type request : Object
        @return:   HttpResponse or Redirect the another URL
    '''
    json_data = {}
    if request.method == "GET":
        if kwargs['sub_module_name'] == "AppAdmin" or kwargs['sub_module_name'] == "HRMS":
            template_name = 'help_topics/' + kwargs['module_name'] + '/Introduction.html'
        else:
            template_name = 'help_topics/' + kwargs['module_name'] + '/' + kwargs['sub_module_name'] + '.html'
        json_data['posts'] = loader.render_to_string(template_name)
        json_data['status'] = "NTE_01"
    else:
        logger_obj.info("Data management data inserted api method not support " + str(request.user.username))
        json_data["status"] = status_keys.ERR0405
    return HttpResponse(json.dumps(json_data))

templates/help_topics/help_content_app_info.html
{% extends 'base.html' %} {% load base_tags %} {% load staticfiles %}
{% block links %}
<link href="{% static '/dev/help_topics/css/help_topic.css' %}"
	rel="stylesheet" type="text/css" />
{% endblock %} {% block content %} {% nav_tags %}
<!-- BEGIN CONTAINER -->
<div id="menuOverlay" class="backgroundfix">
	<div class="page-container margin-0" id="maincontent">
		<!-- BEGIN CONTENT -->
		<div class="page-content-wrapper">
			<!-- BEGIN CONTENT BODY -->
			<div class="page-content">
				<!-- BEGIN PAGE BASE CONTENT -->
				<div class="row">
					<div class="col-md-12">
						<div class="portlet light bordered"
							id="blockui_sample_1_portlet_body">
							<div class="portlet-title">
								<div class="caption">
									 <span class="caption-subject bold">NEXT
										Human Capital Management System</span>
								</div>
							</div>
							<div class="row">
								<div class="col-sm-12 col-md-12">
									<div class="panel panel-default">
										<div class="panel-heading">
											<h3 class="panel-title">Human Capital Management System</h3>
										</div>
										<div class="panel-body">Human Capital Management
											software is basically designed in a way to maximize the
											efficiency in the organization work by accuracy in workflow &
											resolving timing issues. It has specifically assigned the
											authorities & rights for every single user. Provide
											automation & streamlined flow to all day-to-day tasks. Single
											database system provides centralized managements.</div>
									</div>
								</div>
							</div>
							<div class="row">
								<div class="col-md-3">
									<div class="panel panel-default">
										<!-- Default panel contents -->
										<div class="panel-heading">
											<a href="{% url 'help_content:help_content_details' 'SysAdmin' %}">
												<h3 class="panel-title">AppAdmin</h3>
											</a>
										</div>
										<div class="panel-body">
											<p style="text-align: justify">The AppAdmin facilitates
												the data management, user, access management and also to
												manage the application data. Data management is a
												configuration module to set up the master data.</p>
										</div>
										<!-- List group -->
										<ul class="list-group">
											<li class="list-group-item">Data Management<span>
											</span>
											</li>
											<li class="list-group-item">Manage Application Data<span>
											</span>
											</li>
											<li class="list-group-item">User & Access Management<span>
											</span>
											</li>
										</ul>
									</div>
								</div>
								<div class="col-md-3">
									<div class="panel panel-default">
										<!-- Default panel contents -->
										<div class="panel-heading">
										<a href="{% url 'help_content:help_content_details' 'TalentAssessment' %}">
												<h3 class="panel-title">Talent Assessment</h3>
											</a>
										</div>
										<div class="panel-body">
											<p style="text-align: justify">The fundamental goal of
												talent assessment and feedback is to promote and improve
												employee effectiveness. Help towards achievement of superior
												standards of work performance.</p>
										</div>
										<!-- List group -->
										<ul class="list-group">
											<li class="list-group-item">Goal Management<span>
											</span>
											</li>
											<li class="list-group-item">Goal Alignment<span>
											</span>
											</li>
											<li class="list-group-item">Goal Cascading<span>
											</span>
											</li>
										</ul>
									</div>
								</div>
								<div class="col-md-3">
									<div class="panel panel-default">
										<!-- Default panel contents -->
										<div class="panel-heading">
											<h3 class="panel-title">Talent Development</h3>
										</div>
										<div class="panel-body">
											<p style="text-align: justify">Talent Development enables
												all the employees to develop their skills in which they are
												expertized. It enables them to the next level to elevation.</p>
										</div>
										<!-- List group -->
										<ul class="list-group">
											<li class="list-group-item"><a href="">Holiday List</a></li>
											<li class="list-group-item"><a href="">Manage Leave
													Balance</a></li>
											<li class="list-group-item"><a href="">Leave Request</a></li>
										</ul>
									</div>
								</div>
								<div class="col-md-3">
									<div class="panel panel-default">
										<!-- Default panel contents -->
										<div class="panel-heading">
											<h3 class="panel-title">Talent Management</h3>
										</div>
										<div class="panel-body">
											<p style="text-align: justify">Talent management is the
												proactive identification and development of high potential
												individuals, at all levels of an organisation, to support
												them to reach their full potential.</p>
										</div>
										<!-- List group -->
										<ul class="list-group">
											<li class="list-group-item"><a href="">Talent
													Inventory</a></li>
											<li class="list-group-item"><a href="">Succession
													Planning</a></li>
											<li class="list-group-item"><a href="">Track Process</a></li>
										</ul>
									</div>
								</div>
							</div>
							<div class="row">	
								<div class="col-md-3">
									<div class="panel panel-default">
										<!-- Default panel contents -->
										<div class="panel-heading">
											<a href="{% url 'help_content:help_content_details' 'HRMS' %}">
												<h3 class="panel-title">HRMS</h3>
											</a>
										</div>
										<div class="panel-body">
											<p style="text-align: justify">A Human Resources
												Management System combines many human resources functions,
												including benefits administration, payroll, recruiting and
												training, and performance analysis and review</p>
										</div>
										<!-- List group -->
										<ul class="list-group">
											<li class="list-group-item"><a href="">Employee
													Management</a></li>
											<li class="list-group-item"><a href="">Leave
													Management</a></li>
											<li class="list-group-item"><a href="">Organization
													Unit</a></li>
										</ul>
									</div>
								</div>
								<div class="col-md-3">
									<div class="panel panel-default">
										<!-- Default panel contents -->
										<div class="panel-heading">
											<h3 class="panel-title">Talent Acquistion</h3>																						
										</div>
										<div class="panel-body">
											<p style="text-align: justify">Talent Acquisition is the
												process of attracting and hiring skilled employees to
												fulfill a company’s business needs. Proactively build
												applicant pipelines to meet current and future business
												needs. </p>
										</div>
										<!-- List group -->
										<ul class="list-group">
											<li class="list-group-item"><a href="">Reference
													Item Category</a></li>
											<li class="list-group-item"><a href="">Reference
													items</a></li>
											<li class="list-group-item"><a href="">Data Access</a></li>
										</ul>
									</div>
								</div>
								<div class="col-md-3">
									<div class="panel panel-default">
										<!-- Default panel contents -->
										<div class="panel-heading">
										<a href="{% url 'help_content:help_content_details' 'WorkforcePlanning' %}">
												<h3 class="panel-title">Workforce Planning</h3>
											</a>
											</div>
										<div class="panel-body">
											<p>Workforce planning is a continual process used to
												align the needs and priorities of the organization with
												those of its workforce to ensure</p>
										</div>
										<!-- List group -->
										<ul class="list-group">
											<li class="list-group-item"><a href="">SSM Details</a></li>
											<li class="list-group-item"><a href="">Module
													details</a></li>
											<li class="list-group-item"><a href="">Help content</a></li>
										</ul>
									</div>

								</div>
								<div class="col-md-3">
									<div class="panel panel-default">
										<!-- Default panel contents -->
										<div class="panel-heading">
											<a href="{% url 'help_content:help_content_details' 'TalentDefinition' %}">
												<h3 class="panel-title">Talent Definition</h3>
											</a>										
										</div>
										<div class="panel-body">
											<p>In the employee’s page, the user can view their
												details and the HR can add, update or remove the employee
												details.</p>
										</div>
										<!-- List group -->
										<ul class="list-group">
											<li class="list-group-item">Primary Information<span>
											</span>
											</li>
											<li class="list-group-item">Personal Management<span>
											</span>
											</li>
											<li class="list-group-item">HR Setting<span> </span>
											</li>
										</ul>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<!-- END PAGE BASE CONTENT -->
			</div>
			<!-- END CONTENT BODY -->
		</div>
		<!-- END CONTENT -->
	</div>
</div>
<!-- END CONTAINER -->
{% endblock %}

templates/help_topics/help_content_info.html
{% extends 'base.html' %} {% load base_tags %} {% load staticfiles %} 
{% block links %}
<link href="{% static '/dev/help_topics/css/help_topic.css' %}"
	rel="stylesheet" type="text/css" />
{% endblock %} {% block content %} {% nav_tags %}
<!-- BEGIN CONTAINER -->
<div id="menuOverlay" class="backgroundfix">
	<div class="page-container margin-0" id="maincontent">
		<!-- BEGIN CONTENT -->
		<div class="page-content-wrapper">
			<!-- BEGIN CONTENT BODY -->
			<div class="page-content">
				<!-- BEGIN PAGE BASE CONTENT -->
				<div class="row">
					<div class="col-md-12">
						<div class="portlet light bordered"
							id="blockui_sample_1_portlet_body">
							<div class="portlet-title">
								<div class="caption">
									<span class="caption-subject bold">NEXT
										Human Capital Management System</span>
								</div>
							</div>
							<div class="row">
								<div class="col-sm-12 col-md-12">
									<div class="panel panel-info">
										<div class="panel-heading">
											<h3 class="panel-title">Get Started</h3>
										</div>
										<div class="panel-body">Our NEXT Human Capital Management System is a collection of resources—all the knowledge, talents, skills, abilities, experience, intelligence, training, judgment, and wisdom possessed individually and collectively by individuals in an organization. HCMS would enable and empower the Organization to manage the talent and the talent pool to have a progressive career build in the organization.</div>
									</div>
								</div>
							</div>
							<!-- End Col -->
							<div class="row">
								<div class="col-sm-6 col-md-4">
									<div class="col-md-12 feature-box">
										<span class="glyphicon glyphicon-user icon"></span>
										<h4>Start Your Subscription</h4>
										<p>Order NEXT Applications</p>
										<p>Activate your order</p>
										
										<button type="button" class="btn btn-success btn-animate site-btn" onclick="location.href='{% url 'help_content:help_content_page1' %}'">Start
											Right Now</button>

									</div>
								</div>
								<!-- End Col -->
								<div class="col-sm-6 col-md-4">
									<div class="col-md-12 feature-box">
										<span class="glyphicon glyphicon-cog icon"></span>
										<h4>Learn What's New</h4>
										<p>Review New Features</p>
										<p>Learn More</p>
										<button type="button" class="btn btn-primary btn-animate site-btn" onclick="location.href='{% url 'help_content:help_content_page1' %}'">Start
											Right Now</button>
									</div>
								</div>
								<!-- End Col -->
								<div class="col-sm-6 col-md-4">
									<div class="feature-box">
										<span class="glyphicon glyphicon-bell icon"></span>
										<h4>Join Communities</h4>
										<p>Join NEXT Support Community</p>
										<p>Join NEXT Customer Connect</p>
										<button type="button" class="btn btn-danger btn-animate site-btn" onclick="location.href='{% url 'help_content:help_content_page1' %}'">Start
											Right Now</button>
									</div>
								</div>
								<!-- End Col -->
							</div>
							<!-- End row -->
						</div>
					</div>
				</div>
				<!-- END PAGE BASE CONTENT -->
			</div>
			<!-- END CONTENT BODY -->
		</div>
		<!-- END CONTENT -->
	</div>
</div>
<!-- END CONTAINER -->
{% endblock %}